package Projeto_Surpresa;

import java.awt.Color;
import java.awt.Cursor;
import java.awt.EventQueue;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.DefaultComboBoxModel;
import javax.swing.GroupLayout;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import javax.swing.LayoutStyle;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.WindowConstants;
import javax.swing.border.BevelBorder;

public class Howard_surpresa {

   
    public static void main(String[] args) {
        
        
        Roupas r1 = new Roupas();
        r1.setCor("Vermelha");
        r1.setDescricao("Camisa Xadrez");
        r1.setFavorita(Boolean.TRUE);
        r1.setTipo("Camisa");
        
        Roupas r2 = new Roupas();
        r2.setCor("Azul");
        r2.setDescricao("Camisa Xadrez");
        r2.setFavorita(Boolean.FALSE);
        r2.setTipo("Camisa");
        
        Roupas r3 = new Roupas();
        r3.setCor("Verde");
        r3.setDescricao("Camisa Xadrez");
        r3.setFavorita(Boolean.FALSE);
        r3.setTipo("Camisa");
        
        
        Roupas cam1 = new Roupas();
        cam1.setCor("Vermelha");
        cam1.setDescricao("Camiseta");
        cam1.setFavorita(Boolean.FALSE);
        cam1.setTipo("Camiseta");
        
        Roupas cam2 = new Roupas();
        cam2.setCor("Azul");
        cam2.setDescricao("Camiseta");
        cam2.setFavorita(Boolean.FALSE);
        cam2.setTipo("Camiseta");
        
        Roupas cal = new Roupas();
        cal.setCor("Azul");
        cal.setDescricao("Calça Jeans");
        cal.setFavorita(Boolean.FALSE);
        cal.setTipo("Calça");
        
        
        Fantasia fc = new Fantasia();
        fc.setNome("Camisa do Superman");
        fc.setCor("Azul");
        fc.setFavorita(Boolean.FALSE);
        fc.setDescricao("Camisa");
        fc.setTipo("Fantasia");
        
        Fantasia fb = new Fantasia();
        fb.setNome("Bermuda do Coringa");
        fb.setCor("Verde");
        fb.setFavorita(Boolean.FALSE);
        fb.setDescricao("Bermuda");
        fb.setTipo("Fantasia");
        
        
        Astronauta a = new Astronauta();
        a.setCodsnasa("1AXBC5");
        a.setDataroupa("18/10/1998");
        a.setCor("Branca");
        a.setDescricao("Camiseta oficial da missão Marte Ataca");
        a.setFavorita(Boolean.TRUE);
        a.setTipo("Roupa de Astronauta");
        
        
        
        Roupeiro ropa = new Roupeiro ();
        ropa.setSetoroupeiro("A - Roupa de Astronauta");
        ropa.lista.add(a);
        
        Roupeiro ropb = new Roupeiro ();
        ropb.setSetoroupeiro("B - Camisas e Calças");
        ropb.lista.add(r1);
        ropb.lista.add(r2);
        ropb.lista.add(r3);
        ropb.lista.add(cam1);
        ropb.lista.add(cam2);
        ropb.lista.add(cal);
        
        Roupeiro ropc = new Roupeiro ();
        ropc.setSetoroupeiro("C - Fantasias");
        ropc.lista.add(fc);
        ropc.lista.add(fb);
        
        Roupeiro ropd = new Roupeiro ();
        ropd.setSetoroupeiro("D - Cuecas e Meias");
        
        Roupeiro rope = new Roupeiro ();
        rope.setSetoroupeiro("E - Sapatos");
        
        
        
        
        JOptionPane.showMessageDialog(null,ropa.mostraroupas());
        JOptionPane.showMessageDialog(null,ropb.mostraroupas());
        JOptionPane.showMessageDialog(null,ropc.mostraroupas());
        JOptionPane.showMessageDialog(null,ropd.mostraroupas());
        JOptionPane.showMessageDialog(null,rope.mostraroupas());
        
        
        
        
        
        
        
    }

    /*
     * To change this license header, choose License Headers in Project Properties.
     * To change this template file, choose Tools | Templates
     * and open the template in the editor.
     */
    /**
     *
     * @author Guilherme
     */
    public static class Tela_howard extends JFrame {

        /**
         * Creates new form Tela_howard
         */
        public Tela_howard() {
            super();
            initComponents();
        }

        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */
        // <editor-fold defaultstate="collapsed" desc="Generated Code">
        @SuppressWarnings(value = "unchecked")
        private void initComponents() {
            jPanel3 = new JPanel();
            jButton1 = new JButton();
            jButton2 = new JButton();
            jButton3 = new JButton();
            jButton4 = new JButton();
            jScrollPane1 = new JScrollPane();
            txt_Nome2 = new JTextArea();
            jLabel5 = new JLabel();
            jLabel6 = new JLabel();
            txt_Nome1 = new JTextField();
            jLabel2 = new JLabel();
            jButton5 = new JButton();
            jButton6 = new JButton();
            Combo = new JComboBox();
            jButton7 = new JButton();
            jLabel3 = new JLabel();
            jButton8 = new JButton();
            jLabel4 = new JLabel();
            txt_Nome = new JTextField();
            setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
            jPanel3.setBorder(BorderFactory.createBevelBorder(BevelBorder.RAISED));
            jButton1.setText("jButton1");
            jButton2.setText("jButton2");
            jButton3.setText("jButton3");
            jButton4.setText("jButton4");
            GroupLayout jPanel3Layout = new GroupLayout(jPanel3);
            jPanel3.setLayout(jPanel3Layout);
            jPanel3Layout.setHorizontalGroup(jPanel3Layout.createParallelGroup(GroupLayout.Alignment.LEADING).addGroup(GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup().addContainerGap(39, Short.MAX_VALUE).addComponent(jButton1).addGap(18, 18, 18).addComponent(jButton2).addGap(18, 18, 18).addComponent(jButton3).addGap(18, 18, 18).addComponent(jButton4).addGap(27, 27, 27)));
            jPanel3Layout.setVerticalGroup(jPanel3Layout.createParallelGroup(GroupLayout.Alignment.LEADING).addGroup(jPanel3Layout.createSequentialGroup().addGap(37, 37, 37).addGroup(jPanel3Layout.createParallelGroup(GroupLayout.Alignment.BASELINE).addComponent(jButton1).addComponent(jButton2).addComponent(jButton3).addComponent(jButton4)).addContainerGap(40, Short.MAX_VALUE)));
            txt_Nome2.setColumns(20);
            txt_Nome2.setRows(5);
            jScrollPane1.setViewportView(txt_Nome2);
            jLabel5.setText("Descri\u00e7\u00e3o:");
            jLabel6.setText("Cor:");
            txt_Nome1.setText("                                                   ");
            txt_Nome1.addActionListener(new ActionListener() {
                public void actionPerformed(ActionEvent evt) {
                    txt_Nome1ActionPerformed(evt);
                }
            });
            jLabel2.setFont(new Font("MV Boli", 0, 24)); // NOI18N
            jLabel2.setForeground(new Color(0, 102, 102));
            jLabel2.setText("Tela howard de roupas");
            jLabel2.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
            jButton5.setText("jButton5");
            jButton6.setText("jButton6");
            Combo.setModel(new DefaultComboBoxModel(new String[]{"Selecione", "Sim", "N\u00e3o:"}));
            jButton7.setText("jButton7");
            jLabel3.setText("Preferida:");
            jButton8.setText("jButton8");
            jLabel4.setText("Tipo:");
            txt_Nome.setText("                                               ");
            txt_Nome.addActionListener(new ActionListener() {
                public void actionPerformed(ActionEvent evt) {
                    txt_NomeActionPerformed(evt);
                }
            });
            GroupLayout layout = new GroupLayout(getContentPane());
            getContentPane().setLayout(layout);
            layout.setHorizontalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING).addGroup(layout.createSequentialGroup().addGap(225, 225, 225).addComponent(jPanel3, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE).addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)).addGroup(GroupLayout.Alignment.TRAILING, layout.createSequentialGroup().addContainerGap(130, Short.MAX_VALUE).addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING).addGroup(GroupLayout.Alignment.TRAILING, layout.createSequentialGroup().addComponent(jLabel2).addGap(284, 284, 284)).addGroup(GroupLayout.Alignment.TRAILING, layout.createSequentialGroup().addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING).addComponent(jLabel4).addComponent(jLabel6)).addGap(18, 18, 18).addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING, false).addGroup(layout.createSequentialGroup().addComponent(jButton5).addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE).addComponent(jButton6).addGap(8, 8, 8)).addComponent(txt_Nome).addComponent(txt_Nome1)).addGap(18, 18, 18).addGroup(layout.createParallelGroup(GroupLayout.Alignment.TRAILING, false).addGroup(layout.createSequentialGroup().addComponent(jLabel3).addGap(18, 18, 18).addComponent(Combo, GroupLayout.PREFERRED_SIZE, 171, GroupLayout.PREFERRED_SIZE)).addGroup(layout.createSequentialGroup().addComponent(jLabel5).addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE).addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)).addGroup(GroupLayout.Alignment.LEADING, layout.createSequentialGroup().addGap(39, 39, 39).addComponent(jButton7).addGap(50, 50, 50).addComponent(jButton8))).addGap(194, 194, 194)))));
            layout.setVerticalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING).addGroup(layout.createSequentialGroup().addGap(49, 49, 49).addComponent(jLabel2).addGap(39, 39, 39).addComponent(jPanel3, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE).addGap(82, 82, 82).addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE).addComponent(Combo, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE).addComponent(jLabel3).addComponent(jLabel4).addComponent(txt_Nome, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)).addGap(18, 18, 18).addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING).addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE).addGroup(layout.createSequentialGroup().addComponent(jLabel5).addGap(4, 4, 4).addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE).addComponent(jLabel6).addComponent(txt_Nome1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)))).addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE).addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE).addComponent(jButton5).addComponent(jButton6).addComponent(jButton7).addComponent(jButton8)).addGap(49, 49, 49)));
            pack();
        } // </editor-fold>

        private void txt_Nome1ActionPerformed(ActionEvent evt) {
            // TODO add your handling code here:
        }

        private void txt_NomeActionPerformed(ActionEvent evt) {
            // TODO add your handling code here:
        }

        /**
         * @param args the command line arguments
         */
        public static void main(String[] args) {
            /* Set the Nimbus look and feel */
            //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
            /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
             * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
             */
            try {
                for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
                    if ("Nimbus".equals(info.getName())) {
                        UIManager.setLookAndFeel(info.getClassName());
                        break;
                    }
                }
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(Tela_howard.class.getName()).log(Level.SEVERE, null, ex);
            } catch (InstantiationException ex) {
                Logger.getLogger(Tela_howard.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IllegalAccessException ex) {
                Logger.getLogger(Tela_howard.class.getName()).log(Level.SEVERE, null, ex);
            } catch (UnsupportedLookAndFeelException ex) {
                Logger.getLogger(Tela_howard.class.getName()).log(Level.SEVERE, null, ex);
            }
            //</editor-fold>
            /* Create and display the form */
            EventQueue.invokeLater(new Runnable() {
                public void run() {
                    new Tela_howard().setVisible(true);
                }
            });
        }
        // Variables declaration - do not modify
        private JComboBox Combo;
        private JButton jButton1;
        private JButton jButton2;
        private JButton jButton3;
        private JButton jButton4;
        private JButton jButton5;
        private JButton jButton6;
        private JButton jButton7;
        private JButton jButton8;
        private JLabel jLabel2;
        private JLabel jLabel3;
        private JLabel jLabel4;
        private JLabel jLabel5;
        private JLabel jLabel6;
        private JPanel jPanel3;
        private JScrollPane jScrollPane1;
        private JTextField txt_Nome;
        private JTextField txt_Nome1;
        private JTextArea txt_Nome2;
        // End of variables declaration
    }
    
}
