/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Admin;

/**
 *
 * @author Guilherme
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem2 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem4 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem5 = new javax.swing.JCheckBoxMenuItem();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        GerenciarPessoa = new javax.swing.JMenuItem();
        ListarPessoa = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        GerenciarCidade = new javax.swing.JMenuItem();
        ListarCidade = new javax.swing.JMenuItem();

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        jCheckBoxMenuItem2.setSelected(true);
        jCheckBoxMenuItem2.setText("jCheckBoxMenuItem2");

        jCheckBoxMenuItem4.setSelected(true);
        jCheckBoxMenuItem4.setText("jCheckBoxMenuItem4");

        jCheckBoxMenuItem5.setSelected(true);
        jCheckBoxMenuItem5.setText("jCheckBoxMenuItem5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("Pessoa");

        GerenciarPessoa.setText("Gerenciar");
        GerenciarPessoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GerenciarPessoaActionPerformed(evt);
            }
        });
        jMenu1.add(GerenciarPessoa);

        ListarPessoa.setText("Listar");
        ListarPessoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListarPessoaActionPerformed(evt);
            }
        });
        jMenu1.add(ListarPessoa);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Cidade");

        GerenciarCidade.setText("Gerenciar");
        GerenciarCidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GerenciarCidadeActionPerformed(evt);
            }
        });
        jMenu2.add(GerenciarCidade);

        ListarCidade.setText("Listar");
        ListarCidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListarCidadeActionPerformed(evt);
            }
        });
        jMenu2.add(ListarCidade);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ListarCidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListarCidadeActionPerformed
               CidadeManter tela = new CidadeManter ();

               tela.setDefaultCloseOperation(DISPOSE_ON_CLOSE);

               tela.setVisible(true);

    }//GEN-LAST:event_ListarCidadeActionPerformed

    private void GerenciarPessoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GerenciarPessoaActionPerformed
       PessoaManter tela = new PessoaManter ();
       tela.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
       tela.setVisible(true);
        
    }//GEN-LAST:event_GerenciarPessoaActionPerformed

    private void GerenciarCidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GerenciarCidadeActionPerformed
       CidadeManter tela = new CidadeManter ();
       tela.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
       tela.setVisible(true);
            }//GEN-LAST:event_GerenciarCidadeActionPerformed

    private void ListarPessoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListarPessoaActionPerformed
       PessoaManter tela = new PessoaManter ();
       tela.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
       tela.setVisible(true);
            }//GEN-LAST:event_ListarPessoaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem GerenciarCidade;
    private javax.swing.JMenuItem GerenciarPessoa;
    private javax.swing.JMenuItem ListarCidade;
    private javax.swing.JMenuItem ListarPessoa;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem2;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem4;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
